### ISSUE TITLE
xmutil boardid -b som

### ISSUE THREAD

**Issue by DoiTakahiro** [Xilinx/xmutil#6]
my k26som eeprom address = 0x7d value = 0xee
error occured!
```
xmutil boardid -b som
Traceback (most recent call last):
  File "/usr/bin/fru-print", line 46, in <module>
    print(yaml.dump(load(eval(args.board)), default_flow_style=False, allow_unicode=True))
  File "/usr/lib/python3.9/site-packages/fru/fru_format.py", line 138, in load
    data['board'].update(extract_values(blob, board_offset + 6, names))
  File "/usr/lib/python3.9/site-packages/fru/fru_format.py", line 64, in extract_values
    data['custom_fields'].append(blob[offset + 1:offset + length + 1].decode('ascii'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 1: ordinal not in range(128)
```

**Comment by chkohn** [comment]
@DoiTakahiro are you running this on a Ubuntu or on a PetaLinux/Yocto image? Also make sure you use sudo when running the command. It appears to me you are using an old version of xmutil. If you are running Ubuntu, make sure you update to the latest version by running 'apt update' followed by 'apt upgrade'. If you are running PetaLinux or Yocto, what image version are you using? I suggest you use the latest release image which can be found here: https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/1641152513/Kria+SOMs+Starter+Kits#Starter-Kit-Pre-Built-Software

**Comment by DoiTakahiro** [comment]
Thank you for your response. I am using a customized build of PetaLinux 2022.2.
To install the latest version of xmutil with petalinux-build, what should I do?

**Comment by DoiTakahiro** [comment]
After running petalinux-build, when I created the SD card, xmutil boardid -b som worked fine in the freshly created state. Perhaps dnf update is suspicious. I'll investigate it.

**Comment by DoiTakahiro** [comment]
"I couldn't determine when xmutil boardid -b som started to produce errors, even though it was working fine initially."
